-- mm.lua
-- Переводы для интерфейса и игровых элементов

local translations = {
	-- Погода
	["Clear"] = "Ясная",
	["Cloudy"] = "Облачная",
	["Night"] = "Ночь",
	["Rain"] = "Дождь",

	-- Сложность
	["gd_master"] = "Мастер",
	["gd_novice"] = "Новичок",
	["gd_veteran"] = "Ветеран",
	["gd_stalker"] = "Сталкер",
	["st_opt_high"] = "Высоко",
	["st_opt_low"] = "Низко",
	["st_opt_medium"] = "Средне",
	["st_opt_off"] = "Отключено",
	["st_opt_extreme"] = "Макс. высоко",
	["st_opt_ultra"] = "Очень высоко",

	-- Интерфейс
	["game type"] = "ТИП ИГРЫ",
	["icon"] = "Значки",
	["map"] = "КАРТА",
	["version"] = "Версия",

	-- Меню и действия
	["ui_mm_action"] = "Действие",
	["ui_mm_advanced"] = "Расширенные",
	["ui_mm_alternative"] = "Альтернатив.",
	["ui_mm_back"] = "Назад",
	["ui_mm_blood"] = "Кровь",
	["ui_mm_ok"] = "OK",
	["ui_mm_next"] = "След.",
	["ui_mm_previous"] = "Пред.",
	["ui_mm_craft"] = "Создать",
	["ui_mm_upgrade"] = "Модифицировать",
	["ui_mm_repair"] = "Отремонтировать",
	["ui_mm_cook"] = "Приготовить",
	["ui_mm_loot_selected"] = "Взять выбранное",
	["ui_mm_loot_all"] = "Взять всё (Enter)",
	["ui_mm_check_updates"] = "Обновления",
	["ui_mm_controls"] = "Управление",
	["ui_mm_credits"] = "Титры",
	["ui_mm_delete"] = "Удалить",
	["ui_mm_delete_existing_file_q"] = "Вы действительно хотите удалить этот файл?",
	["ui_mm_difficulty"] = "Сложность",
	["ui_mm_disconnect"] = "Отсоединиться",
	["ui_mm_disconnect_message"] = "Вы действительно желаете отсоединиться?",
	["ui_mm_key"] = "Кнопка",
	["ui_mm_keyboard_setup"] = "Настройки клавиатуры",
	["ui_mm_last_save"] = "Посл. сохранение",
	["ui_mm_load"] = "Загрузить",
	["ui_mm_load_game"] = "Загрузить игру",
	["ui_mm_continue"] = "ПРОДОЛЖИТЬ",
	["ui_mm_menu_mcm"] = "МЕНЮ МСМ",
	["ui_mm_logout"] = "Выйти из профиля",
	["ui_mm_master"] = "Мастер",
	["ui_mm_need_restart"] = "Изменения вступят в силу только после перезагрузки игры",
	["ui_mm_network_game"] = "Сетевая игра",
	["ui_mm_newgame"] = "Новая игра",
	["ui_mm_novice"] = "Новичок",
	["ui_mm_options"] = "ОПЦИИ",
	["ui_mm_particles_distance"] = "Дальность частиц",
	["ui_mm_quality_presets"] = "Установки качества",
	["ui_mm_quit2windows"] = "!Выйти в Windows",
	["ui_mm_quit_game"] = "Завершить игру",
	["ui_mm_exit_menu"] = "ЗАКОНЧИТЬ ИГРУ",
	["ui_mm_quit_game_message"] = "Вы действительно желаете покинуть игру?",
	["ui_mm_quit_windows_message"] = "Вы действительно хотите выйти в Windows?",
	["ui_mm_return_game"] = "Вернуться в игру",
	["ui_mm_save"] = "Сохранить",
	["ui_mm_save_game"] = "Сохранить игру",
	["ui_mm_stalker"] = "Сталкер",
	["ui_mm_veteran"] = "Ветеран",
	["ui_st_reset"] = "Сбросить",
	["ui_st_sell_all"] = "Продать всё",

	-- Режимы игры
	["st_cap_check_story"] = "Сюжетный режим",
	["st_cap_check_survival"] = "Режим выживания (Beta)",
	["st_cap_check_hardcore"] = "«Одна жизнь»",
	["ui_mm_hardcore"] = "«Одна жизнь»",
	["st_cap_check_azazel_mode"] = "«Жизнь после жизни»",

	-- Дополнительные настройки
	["ui_mm_only_campfire"] = "Сохранение: костры",
	["ui_mm_environment_effect"] = "Доп. погодные эффекты",
	["ui_mm_faction_sel"] = "Специализация",
	["ui_mm_disanim"] = "Вкл./выкл. анимации исп. предметов",
	["ui_mm_character_name"] = "Имя персонажа",
	["ui_mm_transitions_closed_disable"] = "Открыть переходы",
	["ui_mm_confirm_changes"] = "Применить изменения? Все изменения будут отменены через",
}

return translations
